### PR TITLE
toDomCompare

### PR DESCRIPTION
**Pull request by IlanFrumer**
I need to use this https://www.npmjs.com/package/dom-compare

### CODE REVIEW

**Comment by mradionov** [comment]
@IlanFrumer , 
It seems to me as a standalone library which has nothing to do with Jasmine. Do you use it with custom matchers?

**Comment by IlanFrumer** [comment]
@mradionov 

Yes, I use it as a custom matcher.
You can also provide a configuration object to extend the matchers.

**Comment by mradionov** [comment]
I'm not quite sure it's a good idea to put a logic for custom matchers in the reporter, because everybody has their own custom matchers with their own expectation messages and implementations. But I'll think about adding an option to configuration (karma.conf.js), where you could add your own project-specific extra rules to highlight diffs.

**Comment by IlanFrumer** [comment]
@mradionov configuration works for me

**Comment by IlanFrumer** [comment]
Moved to #2

**Pull request closed without merging**
